"use client";
import Link from "next/link";
import { ChevronDown, Menu, X } from "lucide-react";
import { useEffect, useState } from "react";
const menus=[
  {label:"Services",href:"/services",items:[["Meta Ads","/services/meta-ads"],["Google Ads","/services/google-ads"],["SEO","/services/seo"],["Local SEO","/services/local-seo"],["Analytics & Tracking","/services/analytics"],["Web Development","/services/web-development"]]},
  {label:"Case Studies",href:"/case-studies",items:[["Hydrella Beauty Science","/case-studies/hydrella-beauty-science"],["Real Estate Lead Generation","/case-studies/real-estate-lead-generation"],["KokanBag Mango Pulp","/case-studies/kokanbag-mango-pulp"],["ElintOm CRM","/case-studies/elintom-crm"]]},
  {label:"Resources",href:"/resources",items:[["Creative Library","/creative-library"],["Experiments","/experiments"],["Results Dashboard","/results"],["Industries","/industries"],["Insights & Blog","/blog"],["Testimonials","/testimonials"]]},
];
export function Navbar(){const [open,setOpen]=useState(false);const [active,setActive]=useState<string|null>(null);const [visible,setVisible]=useState(true);useEffect(()=>{let last=window.scrollY;const scroll=()=>{const now=window.scrollY;setVisible(now<80||now<last);last=now};window.addEventListener("scroll",scroll,{passive:true});return()=>window.removeEventListener("scroll",scroll)},[]);return <header className={`site-header ${visible?'nav-visible':'nav-hidden'}`}><nav className="site-nav shell"><Link href="/" className="brand"><i/>AMOL<span>.</span></Link><div className="site-links"><Link href="/">Home</Link>{menus.map(menu=><div className="nav-menu" key={menu.label} onMouseEnter={()=>setActive(menu.label)} onMouseLeave={()=>setActive(null)}><Link className="nav-page-link" href={menu.href}>{menu.label}</Link><button onClick={()=>setActive(active===menu.label?null:menu.label)} aria-label={`Show ${menu.label} links`} aria-expanded={active===menu.label}><ChevronDown size={13}/></button>{active===menu.label&&<div className="mega-panel">{menu.items.map(([label,href])=><Link key={href} href={href} onClick={()=>setActive(null)}><span>{label}</span><i>↗</i></Link>)}<Link className="mega-all" href={menu.href} onClick={()=>setActive(null)}>View all {menu.label.toLowerCase()} <i>↗</i></Link></div>}</div>)}<Link href="/about-amol-kadam">About</Link><Link href="/contact">Contact</Link></div><Link href="/contact" className="button button-red desktop-cta">Book consultation <span>↗</span></Link><button className="menu-button" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="Toggle navigation">{open?<X size={21}/>:<Menu size={21}/>}</button></nav>{open&&<div className="mobile-menu"><Link href="/" onClick={()=>setOpen(false)}>Home</Link>{menus.map(menu=><details key={menu.label}><summary>{menu.label}<ChevronDown size={14}/></summary><Link className="mobile-menu-all" href={menu.href} onClick={()=>setOpen(false)}>View all {menu.label}</Link>{menu.items.map(([label,href])=><Link key={href} href={href} onClick={()=>setOpen(false)}>{label}</Link>)}</details>)}<Link href="/about-amol-kadam" onClick={()=>setOpen(false)}>About</Link><Link href="/contact" onClick={()=>setOpen(false)}>Contact</Link><Link href="/contact" className="button button-red" onClick={()=>setOpen(false)}>Book consultation <span>↗</span></Link></div>}</header>}
